### ISSUE TITLE
AlphaESS Set Battery Charge disable

### ISSUE THREAD

**Issue by LordBube** [CharlesGillanders/homeassistant-alphaESS#108]
Hey there,
Sometimes I use the "Set battery Charge"-Service at night to charge my battery when the electricity price is really low and when I can anticipate that I will use more electricity the following day. I do that through NodeRed but with the home assistant node and calling the service in the node.
Charging the battery works well and I use the following code:

```
service: alphaess.setbatterycharge
data:
  enabled: true
  cp1start: "02:00"
  cp1end: "05:00"
  cp2start: "00:00"
  cp2end: "00:00"
  chargestopsoc: 100
  serial: XXXXXXXXXXXX (I insert my serial here)
```
  
If I understand the code correctly, I need to set "enabled" to false to turn it off. Correct? If so, this does not seem to work. It is still on in the app and also on cloud.alphaess.com. It also charges the battery the following night if I do not turn it off.

Can someone please look into this or point me in the right direction.

Big thanks by the way to @CharlesGillanders for the awesome integration!!!

**Comment by CharlesGillanders** [comment]
Would you mind trying to use the initial letter capitalised as "False" to disable charging - that's the case that python expects.

**Comment by LordBube** [comment]
Thank you for your quick response. Unfortunately, it is still not working after changing it to False :(

**Comment by wallus** [comment]
I am also having some related problems. I am trying to change the setbatterycharge times in an automation, but I have found that sometimes it does not work. For example, if 'enabled: false', then it won't change it to 'enabled: true' and as per the example below, if 'enable: true', then it won't change the times to new values. I think it works about half the time.

This is my automation code. 

```
  service: setbatterycharge
  service_data:
    serial: XXXXXXXXXXXXXXX (my serial hidden)
    enabled: true
    cp1start: '12:00'
    cp1end: '15:00'
    cp2start: '00:00'
    cp2end: '00:00'
    chargestopsoc: 100
```

Notes:
* only the start and end times (for dp1 and dp2 ) are different to the existing settings
* the YAML editor forces the 'true' value to be lowercase, even if I write it as 'True'.
* I am also changing the setbatterydischarge values in the same automation.
* I didn't see any errors in the logs
